
---
- name: systemd daemon-reload
  systemd:
    daemon_reload: true

- name: restart wildfly
  service:
    name: "{{ wildfly_service_name }}"
    state: restarted

- name: fix perms
  file:
    path: "{{ wildfly_symlink }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    recurse: true

