
wildfly_version: "31.0.1.Final"
wildfly_user: "jboss"
wildfly_group: "jboss"
wildfly_install_dir: "/opt/wildfly"
wildfly_home: "/opt/wildfly/wildfly-{{ wildfly_version }}"
wildfly_symlink: "/opt/wildfly/current"
wildfly_service_name: "wildfly"
wildfly_bind_address: "0.0.0.0"
wildfly_http_port: 8080
wildfly_https_port: 8443
wildfly_mgmt_port: 9990
open_firewall: true
configure_selinux: true
create_mgmt_user: true
mgmt_username: "admin"
mgmt_password: "ChangeMe!123"
wildfly_archive_url: "https://github.com/wildfly/wildfly/releases/download/{{ wildfly_version }}/wildfly-{{ wildfly_version }}.tar.gz"
wildfly_checksum: ""

